import type { PatternTemplate } from "@/core/contracts/patterns";

export const PATTERN_TEMPLATES: PatternTemplate[] = [
  {
    templateId: "sleep-debt-dip",
    category: "ANTECEDENT_CONSEQUENT",
    label: "Short sleep precedes execution dip",
    antecedent: "SLEEP_BELOW_6_5",
    consequent: "NEXT_DAY_SCORE_DIP",
    polarity: "RISK",
    minSupport: 4,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "SLEEP_DEBT_PRECEDES_DIP",
  },
  {
    templateId: "sleep-protects",
    category: "ANTECEDENT_CONSEQUENT",
    label: "Good sleep tends to precede strong execution",
    antecedent: "SLEEP_ABOVE_7_5",
    consequent: "NEXT_DAY_SCORE_HIGH",
    polarity: "PROTECTIVE",
    minSupport: 4,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "SLEEP_PROTECTS_EXECUTION",
  },
  {
    templateId: "monday-overload",
    category: "CONDITIONAL_RATE",
    label: "Mondays tend to be overloaded",
    antecedent: "WEEKDAY_MONDAY",
    consequent: "HIGH_PLANNED_LOAD",
    polarity: "RISK",
    minSupport: 4,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "MONDAY_OVERPLAN",
  },
  {
    templateId: "post-peak-distraction",
    category: "ANTECEDENT_CONSEQUENT",
    label: "Peak day often precedes distraction spike",
    antecedent: "PRIOR_DAY_PEAK",
    consequent: "DISTRACTION_SPIKE",
    polarity: "RISK",
    minSupport: 3,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "POST_PEAK_DISTRACTION",
  },
  {
    templateId: "consecutive-focus-fatigue",
    category: "TEMPORAL_RECURRENCE",
    label: "Three focused days in a row precedes dip",
    antecedent: "CONSECUTIVE_FOCUS_3",
    consequent: "NEXT_DAY_SCORE_DIP",
    polarity: "RISK",
    minSupport: 3,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "CONSECUTIVE_FOCUS_FATIGUE",
  },
  {
    templateId: "recovery-protects",
    category: "ANTECEDENT_CONSEQUENT",
    label: "Recovery day tends to protect next-day execution",
    antecedent: "RECOVERY_DAY",
    consequent: "NEXT_DAY_SCORE_HIGH",
    polarity: "PROTECTIVE",
    minSupport: 3,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "RECOVERY_DAY_PROTECTS_NEXT",
  },
  {
    templateId: "distraction-precedes-dip",
    category: "ANTECEDENT_CONSEQUENT",
    label: "High-distraction days tend to precede execution dips",
    antecedent: "DISTRACTION_SPIKE",
    consequent: "NEXT_DAY_SCORE_DIP",
    polarity: "RISK",
    minSupport: 4,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "DISTRACTION_PRECEDES_DIP",
  },
  {
    templateId: "blocker-chains",
    category: "TEMPORAL_RECURRENCE",
    label: "Blockers tend to recur across consecutive days",
    antecedent: "BLOCKER_PRESENT",
    consequent: "SCORE_DIP_TODAY",
    polarity: "RISK",
    minSupport: 4,
    minWindowDays: 28,
    lookbackWindow: "P56",
    explanationCode: "BLOCKER_CHAINS",
  },
];
