export { STATE_ENGINE_VERSION } from './config'
export { evaluate, type StateEngineInput, type StateEngineResult } from './state-engine'
export { computeDimensions, type DimensionResult } from './state-dimensions'
export { computeStateConfidence } from './state-confidence'
export { classifyMode, assessRisks, type ModeClassification, type RiskAssessment } from './mode-classifier'
export { analyzeTrajectory } from './trajectory-analyzer'
export { detectTransition } from './transition-engine'
export { buildStateExplanation } from './explainability/build-state-explanation'
export { observationContainsFormulaLeak } from './explainability/explanation-templates'
