/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as IdentityRouteImport } from './routes/identity'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CirclesRouteImport } from './routes/circles'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as IndexRouteImport } from './routes/index'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityRoute = IdentityRouteImport.update({
  id: '/identity',
  path: '/identity',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CirclesRoute = CirclesRouteImport.update({
  id: '/circles',
  path: '/circles',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/check-in': typeof CheckInRoute
  '/circles': typeof CirclesRoute
  '/dashboard': typeof DashboardRoute
  '/identity': typeof IdentityRoute
  '/insights': typeof InsightsRoute
  '/onboarding': typeof OnboardingRoute
  '/premium': typeof PremiumRoute
  '/recovery': typeof RecoveryRoute
  '/weekly': typeof WeeklyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/check-in'
    | '/circles'
    | '/dashboard'
    | '/identity'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/weekly'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/check-in'
    | '/circles'
    | '/dashboard'
    | '/identity'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/weekly'
  id:
    | '__root__'
    | '/'
    | '/check-in'
    | '/circles'
    | '/dashboard'
    | '/identity'
    | '/insights'
    | '/onboarding'
    | '/premium'
    | '/recovery'
    | '/weekly'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckInRoute: typeof CheckInRoute
  CirclesRoute: typeof CirclesRoute
  DashboardRoute: typeof DashboardRoute
  IdentityRoute: typeof IdentityRoute
  InsightsRoute: typeof InsightsRoute
  OnboardingRoute: typeof OnboardingRoute
  PremiumRoute: typeof PremiumRoute
  RecoveryRoute: typeof RecoveryRoute
  WeeklyRoute: typeof WeeklyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity': {
      id: '/identity'
      path: '/identity'
      fullPath: '/identity'
      preLoaderRoute: typeof IdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circles': {
      id: '/circles'
      path: '/circles'
      fullPath: '/circles'
      preLoaderRoute: typeof CirclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckInRoute: CheckInRoute,
  CirclesRoute: CirclesRoute,
  DashboardRoute: DashboardRoute,
  IdentityRoute: IdentityRoute,
  InsightsRoute: InsightsRoute,
  OnboardingRoute: OnboardingRoute,
  PremiumRoute: PremiumRoute,
  RecoveryRoute: RecoveryRoute,
  WeeklyRoute: WeeklyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
